name: CI

on: [push, workflow_dispatch]

jobs:

  build:
    runs-on: macos-latest

    steps:
    - name: Download ngrok
      run: curl -o ngrok.zip https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-darwin-amd64.zip && unzip ngrok.zip

    - name: Auth
      run: ./ngrok/ngrok authtoken $NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Enable TS
      run: sudo systemsetup -setremotelogin on

    - name: Enable Remote Desktop Rule
      run: sudo systemsetup -setremotelogin on

    - name: Create Tunnel
      run: ./ngrok/ngrok tcp 3389
